apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeDeployment
  template:
    metadata:
      labels:
        app: nodeDeployment
    spec:
      containers:
        - name: nodejs-app
          image: mar97/k8s-web-server:1.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: LoadBalancer
  selector:
    app: nodeDeployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
